kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # Name of the ClusterRole
  name: postgres-operator-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
